### ISSUE TITLE
Bot Application not replying and giving error 401 (Unauthorized)

### ISSUE THREAD

**Issue by taranais** [CXuesong/BotBuilder.Standard#3]
Same issue in emulator as [#3694](
https://github.com/Microsoft/BotBuilder/issues/3694)

**Comment by CXuesong** [comment]
I've found the missing statement in `MicrosoftAppCredentials.cs`, where the MS AppId and AppPassword should be loaded from `SettingsUtils` static class as default values. This statement is patched on my ported branch, and perhaps has just gone away when I was merging from a newer official branch.

If you are using my ported version of Bot.Connector, then do not forget to call `SettingsUtils.Attach` in your `Startup.ConfigureServices` bootstrap method. Otherwise, refer to MS's official documentation on how to pass your credential information to bot connector library.

**Comment by CXuesong** [comment]
Published [CXuesong.Ported.Microsoft.Bot.Connector 3.12.2.6-int0](https://www.nuget.org/packages/CXuesong.Ported.Microsoft.Bot.Connector/3.12.2.6-int0). If you are using my ported version, then explicitly installing this package should solve the problem.
